const Menu = [
    {
        id: 1,
        image: "https://via.placeholder.com/150?text=Maggi",
        name: "Maggi",
        category: "Lunch",
        price: 50,
        description: "Delicious instant noodles with a flavorful spice mix, perfect for a quick meal.",
    },
    {
        id: 2,
        image: "https://via.placeholder.com/150?text=Paneer+Tikka",
        name: "Paneer Tikka",
        category: "Dinner",
        price: 200,
        description: "Soft paneer cubes marinated with spices and grilled to perfection.",
    },
    {
        id: 3,
        image: "https://via.placeholder.com/150?text=Veg+Burger",
        name: "Veg Burger",
        category: "Snacks",
        price: 80,
        description: "A delicious veg patty served in a soft bun with fresh veggies and sauces.",
    },
    {
        id: 4,
        image: "https://via.placeholder.com/150?text=Chow+Mein",
        name: "Chow Mein",
        category: "Lunch",
        price: 120,
        description: "Stir-fried noodles with fresh vegetables and a savory sauce.",
    },
    {
        id: 5,
        image: "https://via.placeholder.com/150?text=Gulab+Jamun",
        name: "Gulab Jamun",
        category: "Dessert",
        price: 60,
        description: "Soft, sweet dumplings soaked in a fragrant sugar syrup.",
    },
    {
        id: 6,
        image: "https://via.placeholder.com/150?text=Cold+Coffee",
        name: "Cold Coffee",
        category: "Drinks",
        price: 70,
        description: "Chilled and creamy coffee blended with ice and topped with chocolate.",
    },
    {
        id: 7,
        image: "https://via.placeholder.com/150?text=Masala+Dosa",
        name: "Masala Dosa",
        category: "Breakfast",
        price: 100,
        description: "A crispy rice pancake filled with spiced potato masala.",
    },
    {
        id: 8,
        image: "https://via.placeholder.com/150?text=Grilled+Sandwich",
        name: "Grilled Sandwich",
        category: "Breakfast",
        price: 90,
        description: "Toasted bread stuffed with fresh veggies and cheese.",
    },
    {
        id: 9,
        image: "https://via.placeholder.com/150?text=Chicken+Biryani",
        name: "Chicken Biryani",
        category: "Lunch",
        price: 180,
        description: "Aromatic basmati rice cooked with tender chicken and spices.",
    },
    {
        id: 10,
        image: "https://via.placeholder.com/150?text=Fruit+Salad",
        name: "Fruit Salad",
        category: "Snacks",
        price: 50,
        description: "A refreshing mix of seasonal fruits served with a dash of honey.",
    },
    {
        id: 11,
        image: "https://via.placeholder.com/150?text=Lemonade",
        name: "Lemonade",
        category: "Drinks",
        price: 40,
        description: "Fresh and tangy lemonade to quench your thirst.",
    },
    {
        id: 12,
        image: "https://via.placeholder.com/150?text=Chocolate+Brownie",
        name: "Chocolate Brownie",
        category: "Dessert",
        price: 150,
        description: "Rich and fudgy chocolate brownie topped with a scoop of vanilla ice cream.",
    },
];

export default Menu;
