const Menu = [
    {
        id: 1,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScQbYKAQLAi-2QCXQHfKQkAJoDQtngFlAkwy99Lm-TB-8IF3ocT9s7L03rNc-JOn1dRME&usqp=CAU",
        name: "Maggi",
        category: "Lunch",
        price: 50,
        description: "Delicious instant noodles with a flavorful spice mix, perfect for a quick meal.",
    },
    {
        id: 2,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSa0-9DQ0d9dmoEUB-0F8Ln3cr6rYOQJRuVVg&s",
        name: "Paneer Tikka",
        category: "Dinner",
        price: 200,
        description: "Soft paneer cubes marinated with spices and grilled to perfection.",
    },
    {
        id: 3,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfH1xFRLK4Gn0S0nOqxcqi1QH_5NHyojA4Gw&s",
        name: "Veg Burger",
        category: "Snacks",
        price: 80,
        description: "A delicious veg patty served in a soft bun with fresh veggies and sauces.",
    },
    {
        id: 4,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4HxI1R7E3dhr9SxMtJWe4Z-ra9cd5tGgSbw&s",
        name: "Chow Mein",
        category: "Lunch",
        price: 120,
        description: "Stir-fried noodles with fresh vegetables and a savory sauce.",
    },
    {
        id: 5,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXF3TN0NQaQO_vkZwGoIz9C-qRV7uCJnzNVQ&s",
        name: "Gulab Jamun",
        category: "Dessert",
        price: 60,
        description: "Soft, sweet dumplings soaked in a fragrant sugar syrup.",
    },
    {
        id: 6,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPK264eGFAryAEIGeVKu0t67TpmPYQkP5mMA&s",
        name: "Cold Coffee",
        category: "Drinks",
        price: 70,
        description: "Chilled and creamy coffee blended with ice and topped with chocolate.",
    },
    {
        id: 7,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBgggTQPdz965D3DyOVZ3KMMDlOVBPQPINHQ&s",
        name: "Masala Dosa",
        category: "Breakfast",
        price: 100,
        description: "A crispy rice pancake filled with spiced potato masala.",
    },
    {
        id: 8,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGY73GZlVNqmCHvZOFqJORK7k6PZFxFnibGA&s",
        name: "Grilled Sandwich",
        category: "Breakfast",
        price: 90,
        description: "Toasted bread stuffed with fresh veggies and cheese.",
    },
    {
        id: 9,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4o2lCnuVp_xkwD2ogAPSPKfhP5r_vItGTIA&s",
        name: "Chicken Biryani",
        category: "Lunch",
        price: 180,
        description: "Aromatic basmati rice cooked with tender chicken and spices.",
    },
    {
        id: 10,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-mpTmnDZYeHhzY4_yNlvUMbJTeuAAlCZKjQ&s",
        name: "Fruit Salad",
        category: "Snacks",
        price: 50,
        description: "A refreshing mix of seasonal fruits served with a dash of honey.",
    },
    {
        id: 11,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtEbaB896Sb_9Sssv-bsEud1ypbVN5LAx-wA&s",
        name: "Lemonade",
        category: "Drinks",
        price: 40,
        description: "Fresh and tangy lemonade to quench your thirst.",
    },
    {
        id: 12,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNC0YHJ-NnOhXKyBpqqsSuEkjEY6SjYFJW2w&s",
        name: "Chocolate Brownie",
        category: "Dessert",
        price: 150,
        description: "Rich and fudgy chocolate brownie topped with a scoop of vanilla ice cream.",
    },
];

export default Menu;
